/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:652122:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:652122:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:221766:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:221766:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:875014:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:875014:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:589195:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:589195:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:503038:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:503038:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:856539:
  println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2:856539:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:200590:
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider3:200590:

public void slider2d1_change1(GSlider2D source, GEvent event) { //_CODE_:slider2d1:813612:
  println("slider2d1 - GSlider2D >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2d1:813612:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:412975:
  println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider4:412975:

public void slider5_change1(GSlider source, GEvent event) { //_CODE_:slider5:707459:
  println("slider5 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider5:707459:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:319142:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:319142:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 10, 10, 150, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Welcome to Visualizicar");
  label1.setOpaque(false);
  label2 = new GLabel(this, 30, 50, 110, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Car Model");
  label2.setOpaque(false);
  button1 = new GButton(this, 10, 80, 70, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 90, 80, 70, 30);
  button2.setText("Face text");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 90, 120, 70, 30);
  button3.setText("Face text");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 10, 120, 70, 30);
  button4.setText("Face text");
  button4.addEventHandler(this, "button4_click1");
  label3 = new GLabel(this, 40, 160, 90, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("My label");
  label3.setOpaque(false);
  slider1 = new GSlider(this, 120, 190, 90, 30, 10.0);
  slider1.setRotation(PI/2, GControlMode.CORNER);
  slider1.setLimits(0.5, 0.0, 1.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  slider2 = new GSlider(this, 80, 190, 90, 30, 10.0);
  slider2.setRotation(PI/2, GControlMode.CORNER);
  slider2.setLimits(0.5, 0.0, 1.0);
  slider2.setNumberFormat(G4P.DECIMAL, 2);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  slider3 = new GSlider(this, 40, 190, 90, 30, 10.0);
  slider3.setRotation(PI/2, GControlMode.CORNER);
  slider3.setLimits(0.5, 0.0, 1.0);
  slider3.setNumberFormat(G4P.DECIMAL, 2);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  slider2d1 = new GSlider2D(this, 330, 30, 100, 100);
  slider2d1.setLimitsX(0.5, 0.0, 1.0);
  slider2d1.setLimitsY(0.5, 0.0, 1.0);
  slider2d1.setNumberFormat(G4P.DECIMAL, 2);
  slider2d1.setOpaque(true);
  slider2d1.addEventHandler(this, "slider2d1_change1");
  slider4 = new GSlider(this, 330, 180, 100, 40, 10.0);
  slider4.setLimits(0.5, 0.0, 1.0);
  slider4.setNumberFormat(G4P.DECIMAL, 2);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  slider5 = new GSlider(this, 330, 140, 100, 40, 10.0);
  slider5.setLimits(0.5, 0.0, 1.0);
  slider5.setNumberFormat(G4P.DECIMAL, 2);
  slider5.setOpaque(false);
  slider5.addEventHandler(this, "slider5_change1");
  button5 = new GButton(this, 330, 230, 80, 30);
  button5.setText("Face text");
  button5.addEventHandler(this, "button5_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GLabel label3; 
GSlider slider1; 
GSlider slider2; 
GSlider slider3; 
GSlider2D slider2d1; 
GSlider slider4; 
GSlider slider5; 
GButton button5; 
