/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void llow_poly_car_button_click(GButton source, GEvent event) { //_CODE_:llow_poly_car_button:652122:
  selectedCar = low_poly_car;
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:llow_poly_car_button:652122:

public void hatch_button_click(GButton source, GEvent event) { //_CODE_:hatch_button:221766:
  selectedCar = hatch;
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:hatch_button:221766:

public void truck_button_click(GButton source, GEvent event) { //_CODE_:truck_button:875014:
  selectedCar = pickup_truck;
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:truck_button:875014:

public void SUV_button_click(GButton source, GEvent event) { //_CODE_:SUV_button:589195:
  selectedCar = SUV;
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:SUV_button:589195:

public void bcol_change1(GSlider source, GEvent event) { //_CODE_:bcol:503038:
  blueValue = int(bcol.getValueF() * 255);
  println("Blue Value: " + blueValue);
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:bcol:503038:

public void gcol_change1(GSlider source, GEvent event) { //_CODE_:gcol:856539:
  greenValue = int(gcol.getValueF() * 255);
  println("Green Value: " + greenValue);
  println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:gcol:856539:

public void rcol_change1(GSlider source, GEvent event) { //_CODE_:rcol:200590:
  redValue = int(rcol.getValueF() * 255);
  println("Red Value: " + redValue);
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:rcol:200590:

public void rotate_change1(GSlider source, GEvent event) { //_CODE_:rotat:412975:
  println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:rotat:412975:

public void zoom_change1(GSlider source, GEvent event) { //_CODE_:zoom:707459:
  z = zoom.getValueI();
  println("slider5 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:zoom:707459:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:319142:
  isRunning = !isRunning;
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:319142:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:783150:
  appc.background(230);
} //_CODE_:window1:783150:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  llow_poly_car_button = new GButton(this, 10, 86, 70, 30);
  llow_poly_car_button.setText("Sedan");
  llow_poly_car_button.addEventHandler(this, "llow_poly_car_button_click");
  hatch_button = new GButton(this, 90, 86, 70, 30);
  hatch_button.setText("Hatchback");
  hatch_button.addEventHandler(this, "hatch_button_click");
  truck_button = new GButton(this, 90, 124, 70, 30);
  truck_button.setText("Truck");
  truck_button.addEventHandler(this, "truck_button_click");
  SUV_button = new GButton(this, 10, 125, 70, 30);
  SUV_button.setText("SUV");
  SUV_button.addEventHandler(this, "SUV_button_click");
  bcol = new GSlider(this, 120, 190, 90, 30, 10.0);
  bcol.setRotation(PI/2, GControlMode.CORNER);
  bcol.setLimits(0.5, 0.0, 1.0);
  bcol.setNumberFormat(G4P.DECIMAL, 2);
  bcol.setOpaque(false);
  bcol.addEventHandler(this, "bcol_change1");
  gcol = new GSlider(this, 80, 190, 90, 30, 10.0);
  gcol.setRotation(PI/2, GControlMode.CORNER);
  gcol.setLimits(0.5, 0.0, 1.0);
  gcol.setNumberFormat(G4P.DECIMAL, 2);
  gcol.setOpaque(false);
  gcol.addEventHandler(this, "slider2_change1");
  rcol = new GSlider(this, 40, 190, 90, 30, 10.0);
  rcol.setRotation(PI/2, GControlMode.CORNER);
  rcol.setLimits(0.5, 0.0, 1.0);
  rcol.setNbrTicks(6);
  rcol.setNumberFormat(G4P.DECIMAL, 2);
  rcol.setOpaque(false);
  rcol.addEventHandler(this, "slider3_change1");
  rotat = new GSlider(this, 331, 100, 100, 40, 10.0);
  rotat.setLimits(0.5, 0.0, 1.0);
  rotat.setNumberFormat(G4P.DECIMAL, 2);
  rotat.setOpaque(false);
  rotat.addEventHandler(this, "rotate_change1");
  zoom = new GSlider(this, 331, 76, 100, 40, 10.0);
  zoom.setLimits(5, 0, 10);
  zoom.setNbrTicks(5);
  zoom.setNumberFormat(G4P.INTEGER, 0);
  zoom.setOpaque(false);
  zoom.addEventHandler(this, "zoom_change1");
  button5 = new GButton(this, 219, 86, 69, 20);
  button5.setText("Pause");
  button5.addEventHandler(this, "button5_click1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton llow_poly_car_button; 
GButton hatch_button; 
GButton truck_button; 
GButton SUV_button; 
GSlider bcol; 
GSlider gcol; 
GSlider rcol; 
GSlider rotat; 
GSlider zoom; 
GButton button5; 
GWindow window1;
